# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datapoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freq', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('value', models.FloatField()),
            ],
        ),
    ]
