# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapoint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='freq',
            field=models.CharField(choices=[('a', 'a'), ('q', 'q'), ('m', 'm'), ('w', 'w'), ('d', 'd')], default='a', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='datapoint',
            unique_together=set([('freq', 'name', 'date')]),
        ),
    ]
